backend:
  name: github
  repo: luczaki114/netlify-cms-sandbox
  branch: master

media_folder: "static/assets/uploads/"
public_folder: "assets/uploads"

collections:
  - name: menu
    label: Menu
    files:
      - file: "menu/menu.md"
        label: "Menu"
        name: "menu"
        fields:
          - label: Menu Items
            name: menuItems
            widget: menuItems
            field:
              label: Menu Item
              name: menuItem
              widget: menuItem
              fields:
                - { label: Page or Folder, name: pageOrFolder, widget: select, options: ["folder", "path"], default: "path" }
                - { label: Title, name: title, widget: string}
                - { label: Path, name: path, widget: string }
                - { label: Folder, name: folder, widget: relation, collection: pageFolder, searchFields: ["title"], valueField: folderPath}
            

  - label: Page Folder
    name: pageFolder
    folder: page-folders/
    create: true
    fields: 
      - label: Page Folder
        name: pageFolder
        widget: list
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Folder Path, name: folderPath, widget: string}

  - label: "Content Page"
    name: "contentPage"
    folder: "src/pages"
    filter: { field: templateKey, value: "content-page" }
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
      - {label: Folder Path, name: folderPath, widget: relation, collection: pageFolder, searchFields: ["folderPath"], valueField: folderPath}
      - {label: "Path", name: "path", widget: "string", default: "/about"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Banner Image", name: "bannerImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Landing Page"
    name: "landingPage"
    folder: "src/pages"
    filter: { field: templateKey, value: "landing-page" }
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "landing-page"}
      - {label: Folder Path, name: folderPath, widget: relation, collection: pageFolder, searchFields: ["title"], valueField: folderPath}
      - {label: "Path", name: "path", widget: "hidden", default: "/products"}
      - {label: Title, name: title, widget: string}
      - {label: Sub Title, name: subTitle, widget: string}
      - {label: Banner Image, name: bannerImage, widget: image}
      - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
      - {label: Spot Lights, name: spotlights, widget: list, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Path, name: path, widget: string}, {label: Image, name: image, widget: image}]}
      - {label: Features, name: features, widget: list, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Path, name: path, widget: string}, {label: Icon, name: icon, widget: string}]}
    
  - name: presentations
    label: Presentation
    folder: presentations
    slug: "{{slug}}"
    create: true
    fields:
      - {label: Title, name: title, widget: string, tagname: ""}

      - label: Theme
        name: theme
        widget: select
        options:
          - beige
          - black
          - blood
          - league
          - moon
          - night
          - serif
          - simple
          - sky
          - solarized
          - white

      - label: Body
        name: body
        widget: slides
        separator: "\n\n<!--s-->\n\n"

      # - label: "Reveal Options"
      #   name: revealOptions
      #   required: false
      #   fields:
#          - {label: "Show Controls",             name: controls, required: false, widget: boolean, defaultValue: true}
#          - {label: "Show Progress Bar",         name: progress, required: false, widget: boolean, defaultValue: true}
#          - {label: "Change Browser History",    name: history,  required: false, widget: boolean, defaultValue: false}
#          - {label: "Keyboard Shortcuts",        name: keyboard, required: false, widget: boolean, defaultValue: true}
#          - {label: "Enable Overview Mode",      name: overview, required: false, widget: boolean, defaultValue: true}
#          - {label: "Vertically Center Slides",  name: center,   required: false, widget: boolean, defaultValue: true}
#          - {label: "Loop Presentation",         name: loop,     required, false, widget: boolean, defaultValue: true}
#          - {label: ""}
